services:
  - type: web
    name: charchat-app
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.12.0
